config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get "/contact",  to: "home#contact"
  get "/partners",  to: "home#partners"

  get '/admin/dashboard', to: 'admin/dashboard#index'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy", as: "logout"

  resources :locations
  resources :numbers

  post 'notifications/twilio' => 'notifications#twilio'
end

app/models/concerns/cache_invalidator.rb
module CacheInvalidator
  extend ActiveSupport::Concern

  included do

    after_create :invalidate_cache
    after_destroy :invalidate_cache
    after_update :invalidate_cache

    def invalidate_cache
      Rails.cache.clear
    end
  end

end

app/models/location.rb
class Location < ActiveRecord::Base


  after_create :invalidate_cache
  after_destroy :invalidate_cache
  after_update :invalidate_cache

  validates :name, :address, presence: true

  geocoded_by :address
  after_validation :geocode
  acts_as_gmappable

  def gmaps4rails_address
    address
  end

  private

  def invalidate_cache
    Rails.cache.clear
  end

end

app/models/number.rb
class Number < ActiveRecord::Base

  after_create :invalidate_cache
  after_destroy :invalidate_cache
  after_update :invalidate_cache

  phony_normalize :phone_number, :default_country_code => 'US'

  validates :phone_number, presence: true, uniqueness: true

  def self.get_sms_messages
    @client = Twilio::REST::Client.new(ENV["twilio_account_sid"],
                                       ENV["twilio_auth_token"])
    sms_messages = @client.account.sms.messages.list.
        select do |sms|
      sms.status["received"]
    end

    sms_messages.map do |sms|
      sms.from
    end
  end

  def self.create_from_sms
    get_sms_messages.each do |sms|
      Number.create(phone_number: sms[2..-1])
    end unless get_sms_messages.nil?
  end

  def self.valid?(phone_number)
    lookup_client = Twilio::REST::LookupsClient.new(ENV["twilio_account_sid"],
                                                    ENV["twilio_auth_token"])
    begin
      response = lookup_client.phone_numbers.get(phone_number)
      response.phone_number #if invalid, throws an exception. If valid, no problems.
      return true
    rescue => e
      if e.code == 20404
        return false
      else
        raise e
      end
    end
  end

  private

  def invalidate_cache
    Rails.cache.clear
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, :email, :password, presence: true

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :require_login

  def require_login
    render file: "/public/404" unless current_user
  end

  def index
    @user = User.find(current_user.id)
    @numbers = Number.all
    @locations = Location.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/concerns/webhookable.rb
# module Webhookable
#   extend ActiveSupport::Concern
#   def set_header
#     response.headers["Content-Type"] = "text/xml"
#   end
#
#   def render_twiml(response)
#     render text: response.text
#   end
# end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def contact

  end

  def partners

  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
    @json = @locations.to_gmaps4rails do |location, marker|
      marker.infowindow render_to_string(:partial => "/locations/infowindow", :locals => { :location => location})
      marker.title "#{location.name}"
      marker.json({ :address => location.address})
    end
  end

  def new
    @location = Location.new
  end

  def show
    @location = Location.find(params[:id])
    @json = @location.to_gmaps4rails
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:success] = "Location created."
      redirect_to admin_dashboard_path
    else
      flash.now[:warning] = @location.errors.full_messages.join(". ")
      render :new
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.delete
    redirect_to admin_dashboard_path
  end

  def edit
    if current_user
      @location = Location.find(params[:id])
    else
      redirect_to root_path
      flash[:error] = "Only the site administrator can update the information for a location."
    end

  end

  def update
    @location = Location.find(params[:id])
    if current_user
      if @location.update(name: params[:location][:name],
                          address: params[:location][:address],
                          phone_number: params[:location][:phone_number],
                          email:  params[:location][:email],
                          description: params[:location][:description])
        redirect_to admin_dashboard_path
        flash[:success] = "Location updated!"
      else
        flash[:error] = "Invalid input - Please try updating trip again"
        render :edit
      end
    else
      flash[:error] = "Only the site administrator can update the information for a location."
    end
  end

  private

  def location_params
    params.require(:location)
        .permit(:name, :address, :latitude, :longitude, :description, :email,
                :phone_number, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday)
  end

end

app/controllers/notifications_controller.rb
# require 'twilio-ruby'

class NotificationsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def twilio
    Notify.day_check

    redirect_to admin_dashboard_path
  end


end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController

  def new
    @number = Number.new
  end

  def create
    @number = Number.new(number_params)
    if Number.valid?(@number.phone_number.delete '-, +')
      if @number.save
        flash[:success] = "Your phone number has been registered."
        redirect_to root_path
      else
        flash.now[:warning] = @number.errors.full_messages.join(". ")
        render :new
      end
    else
      flash.now[:warning] = "That number is not a valid number"
      redirect_to root_path
    end
  end

  def index

  end

  def destroy
    @number = Number.find(params[:id])
    @number.delete
    redirect_to admin_dashboard_path
  end

  private

  def number_params
    params.require(:number)
        .permit(:phone_number, :email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id

      flash[:notice] = "Hello Mr. Admin!"
      redirect_to admin_dashboard_path
    else
      flash[:error] = "Invalid login credentials"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Hello #{@user.username}!"
      redirect_to root_path
    else
      flash[:error] = "Invalid input - Please try creating user again"
      render :new
    end
  end

  def index
    @user = User.find(current_user.id)
  end


  private

  def user_params
    params.require(:user).permit(:username, :password, :full_name, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/index.html.erb
<br>
<br>
<br>
<br>

<div class="container">
  <ol class="breadcrumb">
    <li class="active">All Registered Phone Numbers</li>
  </ol>
  <h3 class="text-center">All Registered Phone Numbers</h3>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="nav nav-pills" role="tablist">
        <li role="presentation">
        </li>
      </ul>
    </div>
  </div> <!-- /row -->
  <br>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>ID</th>
        <th>Phone Number</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
          <% @numbers.each do |number| %>
              <tr>
                <td>
                  <%= number.id %>
                </td>
                <td><%= number_to_phone(number.phone_number.delete '-, +')[1..-1] %></td>
                <td><%= link_to "Delete", number_path(number), method: :delete %></td>
              </tr>
          <% end %>
      </tbody>
    </table>

  </div>

  <hr class="featurette-divider"><br>
  <ol class="breadcrumb">
    <li class="active">All Registered Locations</li>
  </ol>

  <h3 class="text-center">All Registered Locations</h3>

  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
          <% @locations.each do |location| %>
              <tr>
                <td><%= location.id %></td>
                <td><%= location.name %></td>
                <td><%= location.address %></td>
                <td><%= link_to "Edit", edit_location_path(location) %></td>
                <td><%= link_to "Delete", location_path(location), method: :delete %></td>
              </tr>
          <% end %>
      </tbody>
    </table>

  </div>
</div>
<br>
<br>
<div style="text-align: center">
  <a href="<%= new_location_path %>" class="btn btn-primary btn-lg btn-danger">Add a Location</a>
</div>
<br>

<div style="text-align: center">
  <%= link_to "Twilio Test Button", notifications_twilio_path, method: :post, class: "btn btn-primary btn-lg" %>
</div><br><br>

app/views/home/contact.html.erb
<br><br><br>

<body>


<header class="header-image">
  <div class="headline">
    <div class="container">
      <h1>Contact Info</h1>
    </div>
  </div>
</header>

<!-- Page Content -->
<div class="container">

  <hr class="featurette-divider">

  <!-- First Featurette -->
  <div class="featurette" id="about">
    <%#= image_tag "Headshot.jpg", class: "featurette-image img-circle img-responsive pull-right" %>
    <h2 class="featurette-heading">
      <span class="text-muted"></span>
    </h2>
    <p class="lead">MealFinder was built by Max Millington.</p>
    <p class="lead">
      Please contact him with any questions concerning the website or if you know of a location offering free meals
      that you would like added to the list.
    <ul class="list-inline">
      <li>
        <a href="mailto:maxmillington89@gmail.com"
           class="btn-social btn-outline btn-lg"><i class="fa fa-fw fa-envelope"></i></a>
      </li>
      <li>
        <a class="btn-social btn-outline btn-lg" href = "javascript:void(0)"onclick = "document.getElementById('light').style.display='block';document.
                getElementById('fade').style.display='block'"><i id="popup" class="fa fa-fw fa-phone popup"></i></a>
        <div id="light" class="white_content">570-690-2302
          <a href = "javascript:void(0)" onclick = "document.getElementById('light').
                  style.display='none';document.getElementById('fade').style.display='none'"><br><br>Close</a></div>
      </li>
      <li>
        <a href="https://github.com/MaxMillington/meal-finder" target="_blank"
           class="btn-social btn-outline btn-lg"><i class="fa fa-fw fa-github"></i></a>
      </li>
    </ul>

    </p>
  </div>

  <hr class="featurette-divider">

</div>
<!-- /.container -->

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

</body>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">


  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/full-width-pics.css" rel="stylesheet">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

<!-- Full Width Image Header with Logo -->
<!-- Image backgrounds are set within the full-width-pics.css file. -->
<header class="image-bg-fluid-height">
  <img class="img-responsive img-center" alt="">
  <img class="img-responsive img-center" alt="">
</header>

<!-- Content Section -->
<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="section-heading">Welcome to MealFinder</h1>
        <p class="lead section-lead">MealFinder was founded with a simple mission, to connect the many food pantries,
          soup kitchens, churches, and non-profits in Denver with those in need. MealFinder sends daily automated text
          messages detailing where and when to get free meals. We also serve as the single best and most comprehensive
          list of where to find meals in Denver. </p>
      </div>
      <div class="col-sm-6"><br>
        <a href="<%= new_number_path %>" class="btn btn-block btn-lg btn-info">Register a Number</a>
      </div>
      <div class="col-sm-6"><br>
        <a href="<%= locations_path %>" class="btn btn-block btn-lg btn-info">View Meal Locations</a>
      </div>
    </div>
  </div>
</section>

<!-- Footer -->
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; MealFinder 2015</p>
      </div>
    </div>
  </div>
  <!-- /.container -->
</footer>

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/home/partners.html.erb
<br><br><br>
<br><br><br>

<body>


<header class="header-image">
  <div class="headline">
    <div class="container">
      <h1>Coming Soon...</h1>
    </div>
  </div>
</header>

<!-- /.container -->

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

</body>

app/views/layouts/_form.html.erb
<br>
<div class="well col-sm-6 col-sm-offset-3">
  <%= form_for @number, url: numbers_path do |f| %>
      <div class="form-group">
        <%= f.label :phone_number, "Phone Number" %>
        <%= f.telephone_field :phone_number, class: "form-control" %>
      </div>
      <%= f.submit "Register", class: "btn btn-success" %>
  <% end %>
  <br><br>
  MealFinder will not share this information with any third parties.
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top navbar-embossed" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">MealFinder</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="<%= partners_path %>">Partners</a>
        </li>
        <li>
          <a href="<%= contact_path %>">Contact</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li>
              <a href="<%= admin_dashboard_path %>">Admin Dashboard</a>
            </li>
            <li>
              <%= link_to "Logout", logout_path, method: :delete %>
            </li>
        <% else %>
            <li>
              <a href="<%= login_path %>">Admin Dashboard</a>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/_notice.html.erb
<% flash.each do |type, message| %>
    <%= content_tag :div, sanitize(message),
                    class: "alert alert-#{type} flash" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MealFinder</title>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <script src="map.js" type="text/javascript"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "layouts/navigation" %>
<%= render partial: "layouts/notice" %>
<%= yield %>
<%= yield :scripts %>

</body>
</html>

app/views/locations/_infowindow.html.erb
<h1><%= location.name %></h1>
<h2>address: <%= location.address %></h2>

app/views/locations/edit.html.erb
<br><br><br><br>
<div class="container">
  <h1 class="text-center">Update Location Information</h1>


  <div class="well col-sm-6 col-sm-offset-3">
    <%= form_for @location, url: location_path(@location) do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :address, "Address" %>
          <%= f.text_field :address, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :phone_number, "Phone Number" %>
          <%= f.telephone_field :phone_number, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :monday, "Monday" %>
          <%= f.text_field :monday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :tuesday, "Tuesday" %>
          <%= f.text_field :tuesday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :wednesday, "Wednesday" %>
          <%= f.text_field :wednesday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :thursday, "Thursday" %>
          <%= f.text_field :thursday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :friday, "Friday" %>
          <%= f.text_field :friday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :saturday, "Saturday" %>
          <%= f.text_field :saturday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :sunday, "Sunday" %>
          <%= f.text_field :sunday, class: "form-control" %>
        </div>
        <%= f.submit "Update Location", class: "btn btn-success" %>
    <% end %>
  </div>

</div>

app/views/locations/index.html.erb
<article><br><br><br><br>
  <body>
  <!-- Page Content -->
  <div class="container">

    <!-- Heading Row -->
    <div class="row">
      <div class="col-md-8">
        <%= gmaps4rails(@json) %>
      </div>

      <!-- /.col-md-8 -->
      <div class="col-md-4">
        <h1>Map of Locations</h1>
        <p>On this page you will find a map of all the locations offering meal assistance in Denver to those in need.
          The list is divided between those locations that offer food-lines, and those that are food banks. <br><br><br>
          Do you know of a location offering free meals that isn't listed? Please click the button below.
        </p>
        <a class="btn btn-primary btn-lg" href="<%= contact_path %>">Contact Site Administrator</a>
      </div>
      <!-- /.col-md-4 -->
    </div>
    <!-- /.row -->

    <hr>

    <!-- Call to Action Well -->
    <div class="row">
      <div class="col-lg-12">
        <div class="well text-center">
          These locations all offer food-line services. Click on the more info button for details.
        </div>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->

    <!-- Content Row -->
    <div class="row well">
      <% @locations.each do |location| %>
          <div id="each-location" class="col-md-4">
            <h2><%= location.name %></h2>
            <p><%= location.address %></p>
            <a class="btn btn-default" href="<%= location_path(location) %>">More Info</a>
          </div>
      <% end %>
    </div>

  </div>
  <!-- /.container -->

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

  </body>



</article>

app/views/locations/new.html.erb
<br><br><br><br>
<div class="container">
  <h1 class="text-center">Register a New Location</h1>

  <div class="well col-sm-6 col-sm-offset-3">
    <p>Please enter the times during which meals are served each day. If meals are not served on a certain day,
      please leave that day blank.</p>
    <%= form_for @location, url: locations_path do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :address, "Address" %>
          <%= f.text_field :address, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :phone_number, "Phone Number" %>
          <%= f.telephone_field :phone_number, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :monday, "Monday" %>
          <%= f.text_field :monday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :tuesday, "Tuesday" %>
          <%= f.text_field :tuesday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :wednesday, "Wednesday" %>
          <%= f.text_field :wednesday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :thursday, "Thursday" %>
          <%= f.text_field :thursday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :friday, "Friday" %>
          <%= f.text_field :friday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :saturday, "Saturday" %>
          <%= f.text_field :saturday, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :sunday, "Sunday" %>
          <%= f.text_field :sunday, class: "form-control" %>
        </div>
        <%= f.submit "Create Location", class: "btn btn-success" %>
    <% end %>
  </div>

</div>

app/views/locations/show.html.erb
<article><br><br><br><br>
  <body>
  <!-- Page Content -->
  <div class="container">

    <!-- Heading Row -->
    <div class="row">
      <div class="col-md-8">
        <%= gmaps4rails(@json) %>
      </div>

      <!-- /.col-md-8 -->
      <div id="location-description" class="col-md-4 well">
        <h1><%= @location.name %></h1>
        <p><%= @location.description %>
        </p>
        <h3>Contact:</h3>
        <p><%= @location.address %></p>
        <p><%= @location.phone_number %></p>
        <br>
        <p><strong>Monday:</strong> <%= @location.monday %></p>
        <p><strong>Tuesday:</strong> <%= @location.tuesday %></p>
        <p><strong>Wednesday:</strong> <%= @location.wednesday %></p>
        <p><strong>Thursday:</strong> <%= @location.thursday %></p>
        <p><strong>Friday:</strong> <%= @location.friday %></p>
        <p><strong>Saturday:</strong> <%= @location.saturday %></p>
        <p><strong>Sunday:</strong> <%= @location.sunday %></p>
        <a class="btn btn-primary btn-lg" href="<%= locations_path %>">Back to All Locations</a>

      </div>
      <!-- /.col-md-4 -->
    </div>
    <!-- /.row -->

    <hr>
    <!-- Content Row -->

  </div>
  <!-- /.container -->

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

  </body>



</article>

app/views/numbers/new.html.erb
<br><br><br><br>
<div class="container">
  <h1 class="text-center">Register Your Phone Number</h1>

<%= render partial: "layouts/form" %>
</div>